version: "3.8"

services:

  expense-app:
    image: shreeya17895/expense-tracker:latest
    container_name: expense-app
    ports:
      - "8081:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - expense-app
      - node-exporter
      - blackbox

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    ports:
      - "9115:9115"
